language: go

sudo: false

env:
  global:
    - GO111MODULE=on

go:
  - "1.12"

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - make setup_ci

script:
  - cd v3 && make build
  - cd v3 && make test
  - cd v3 && go mod vendor && GO111MODULE=off PATH=$TRAVIS_BUILD_DIR/bin:$PATH make lint
